apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: s1ap
  namespace: open5gs
spec:
  NetworkID: s1ap
  NetworkType: ipvlan
  Options:
    host_device: enp0s8
    container_prefix: s1ap
    rt_tables: 250
    vlan: 300
    cidr: 10.10.11.0/28
