apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: gtpc
  namespace: open5gs
spec:
  NetworkID: gtpc
  NetworkType: ipvlan
  Options:
    host_device: enp0s8
    container_prefix: gtpc
    rt_tables: 250
    vlan: 400
    cidr: 192.168.200.0/28
