apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: oam
  namespace: open5gs
spec:
  NetworkID: oam
  NetworkType: ipvlan
  Options:
    host_device: enp0s8
    container_prefix: oam
    rt_tables: 250
    vlan: 300
    cidr: 192.168.200.16/28
