apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu-svc-pool
  namespace: open5gs
  labels:
    epc-mode: sgw-u
spec:
  clusterIP: None   
  selector:
    epc-mode: sgw-u      
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-sgw-u
  namespace: open5gs
  labels:
    epc-mode: sgw-u
spec:
  replicas: 1
  serviceName: "open5gs-sgw-u-svc-pool"
  selector:
    matchLabels:
      epc-mode: sgw-u
  template:
    metadata:
      labels:
        epc-mode: sgw-u
    spec:
      containers:
        - name: sgwu
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v2.1.7
          imagePullPolicy: IfNotPresent
          command: ["open5gs-sgwud", "-c", "/open5gs/config-map/sgwu.yaml"]
          volumeMounts:
            - name: open5gs-sgwu-config
              mountPath: /open5gs/config-map/sgwu.yaml
              subPath: "sgwu.yaml"
      volumes:
        - name: open5gs-sgwu-config
          configMap:
            name: open5gs-sgwu-config
