apiVersion: v1
kind: Service
metadata:
  name: open5gs-smf-svc-pool
  namespace: open5gs
  labels:
    epc-mode: smf
spec:
  clusterIP: None
#  ports:
#  - name: gx
#    port: 3868
#    protocol: TCP  
#  - name: pfcp
#    port: 3868
#    protocol: UDP
  selector:  
    epc-mode: smf        
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: open5gs-smf
  namespace: open5gs
  labels:
    epc-mode: smf
spec:
  replicas: 1
  serviceName: "open5gs-smf-svc-pool"
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:
      labels:
        epc-mode: smf
    spec:
      containers:
        - name: smf
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v2.1.7
          imagePullPolicy: IfNotPresent
          command: ["open5gs-smfd", "-c", "/open5gs/config-map/smf.yaml"]
          volumeMounts:
          - name: open5gs-smf-config
            mountPath: /open5gs/config-map/smf.yaml
            subPath: "smf.yaml"
          - name: open5gs-smf-diameter
            mountPath: /open5gs/config-map/diameter-smf.conf
            subPath: "diameter-smf.conf"               
      volumes:
        - name: open5gs-smf-config
          configMap:
            name: open5gs-smf-config
        - name: open5gs-smf-diameter
          configMap:
            name: open5gs-smf-diameter            
